### PR TITLE
fix: skip release branch push for PATCH releases

### LINKED ISSUE #77: `MakeReleaseTask` attempts to push release branch for PATCH releases, causing push failure
**Description:**
When creating a PATCH release via `MakeReleaseTask`, the task unconditionally calls `gitPushBranch("release/X.X.x")` after `makeRelease()`. However, for PATCH releases, `Releases.createNewRelease(PATCH)` does not create a new branch — it checks out the existing release branch and only creates a new tag. Pushing an already-existing remote branch with `git push -u` fails.

### PR DESCRIPTION
**Pull request by denis-markushin**
Closes: #77

### CODE REVIEW

File: plugin-gradle/src/main/kotlin/com/akuleshov7/vercraft/MakeReleaseTask.kt [hunk 1]
```diff
@@ -44,8 +44,10 @@ abstract class MakeReleaseTask : GitUtilsTask() {
             )
         }
 
-        // Push release branch
-        gitPushBranch(config.get().remote, "release/${version.semVerForBranch()}")
+        // Push release branch (only for MAJOR/MINOR — PATCH reuses an existing branch)
+        if (releaseType.getOrElse(SemVerReleaseType.MINOR) != SemVerReleaseType.PATCH) {
```
Comment (orchestr7) [inline plugin-gradle/src/main/kotlin/com/akuleshov7/vercraft/MakeReleaseTask.kt:48]: Aweseome! Thanks for a fix 👍🏾

**Review by orchestr7 — APPROVED** [review]

**Comment by orchestr7** [comment]
But please check failing tests before merge
